### ISSUE TITLE
Autocomplete window not entirely visible

### ISSUE THREAD

**Issue by BigfootN** [atom-material/atom-material-ui#297]
Hello,

I just noticed that, particularly with this ui theme, the autocomplete window, when the editor is split, is almost hidden under the line number gutter, making it almost impossible to see it:

![2016-06-04-135530_206x97_scrot](https://cloud.githubusercontent.com/assets/1183923/15799792/94a1b468-2a68-11e6-8108-0db941a73f9f.png)

**Steps to reproduce**:

1. Open file
2. Split the screen
3. Place the cursor at the end of a line
4. Write something so that the completion window appears

**Expected behavior**:

This the expected behavior

![2016-06-04-152755_274x176_scrot](https://cloud.githubusercontent.com/assets/1183923/15799799/f981760c-2a68-11e6-9b85-280230593c9a.png)

The window completion is over the line number panel.

**The initial behavior with a gif**:

![out](https://cloud.githubusercontent.com/assets/1183923/15799843/a1f5da48-2a6a-11e6-8492-1083fa84e294.gif)

**The expected behavior**:

![out-1](https://cloud.githubusercontent.com/assets/1183923/15799866/4f9e6192-2a6b-11e6-8c78-083522ffbabc.gif)

**Atom version**: 1.7.4
**OS**: Archlinux

**Installed packages**:

- autocomplete-clang
- autocomplete-paths
- autocomplete-cmake
- file-icons
- linter
- linter-clang
- project-manager

**Configuration**:
```
"atom-material-ui":
    colors:
      abaseColor:
        red: 126
        green: 126
        blue: 126
        alpha: 1
      predefinedColor: "Grey"
    fonts: {}
    tabs:
      compactTabs: true
    treeView:
      blendTabs: true
    ui:
      animations: false
      panelContrast: true
      panelShadows: true
```

**P.S**: The expected behavior was tested with Atom Dark UI theme and my stylesheet is empty.

Thank you very much in advance :)
