### ISSUE TITLE
Can't edit scrollbar width

### ISSUE THREAD

**Issue by calvinkarundu** [atom-material/atom-material-ui#303]
I can't seem to find any settings to edit the width of the scrollbars, not sure if this is the intended behavior or an issue with the package. I just updated to verison 1.2.13 (I'm loving it by the way) running on Ubuntu 14.0.4 and Atom 1.8.0. Everything else looks great though :+1: thank you sir!

**Comment by varughese** [comment]
Check out my pull request !

Or add this to your stylesheet

```css
.scrollbars-visible-always {
     /deep/::-webkit-scrollbar {
         width: 0.2rem;
         height: 0.2rem;
         z-index: 99999;
    }
}
```
