### ISSUE TITLE
Feature request: Allow tabs to span full tab width

### ISSUE THREAD

**Issue by robertrossmann** [atom-material/atom-material-ui#445]
I personally like having my tabs span the full width of the available tab bar instead of being grouped to the left. Atom One Dark theme allows such configuration with the "Tab Sizing: maximum" setting.

It would be awesome if this theme supported such configuration.
Here is a relatively trivial stylesheet which configures the tabs to behave this way:

```less
// Make the tabs span the whole tab bar width
.tab-bar {
  .tab {
    max-width: 100%;
    flex-grow: 2;
    text-align: center;
    // But move the Tree View's tab text to the left. Just a personal taste.
    &[data-type="TreeView"] {
      text-align: left;
    }
  }
}
```

And here's the obligatory screenshot after the change. It looks rather sexy, I'd say. 😍
![tabs-full-width](https://user-images.githubusercontent.com/3058150/31436973-f6d2dffe-ae83-11e7-9646-22b10b47e68d.png)

Thanks for considering implementing this feature!
