### ISSUE TITLE
override `vim-mode-plus` cursor color in normal and visual mode

### ISSUE THREAD

**Issue by mareksuscak** [atom-material/atom-material-ui#453]
Cursor color doesn't match the UI theme's primary color in vim-mode-plus normal mode.

**Reproduction Steps:**

1. install `vim-mode-plus` alongside the `atom-material-ui`
2. enable `Paint text editor's cursor` theme option

**Expected behavior:**

Cursor in vim's normal mode should use the UI theme's primary color.

**Observed behavior:**

Cursor uses the syntax theme's color instead.

**Screenshots and GIFs**

![image](https://user-images.githubusercontent.com/613647/33777151-039acb5a-dc44-11e7-98fa-5749705e9ba2.png)

vs

![image](https://user-images.githubusercontent.com/613647/33777481-485d537e-dc45-11e7-802d-77f384cc7972.png)

**Atom version:** 1.22.1
**OS and version:** MacOS 10.13.2

**Installed packages:**

```
vim-mode-plus
atom-material-ui
```

**Comment by mareksuscak** [comment]
Happy to contribute a patch. Here's the CSS:

```less
atom-text-editor.vim-mode-plus.normal-mode,
atom-text-editor.vim-mode-plus.visual-mode {
  &.is-focused {
    .cursor {
      background-color: #fff !important;
    }
  }
}
```
